# Generated by Django 5.2.15 on 2026-06-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('man', 'Man'), ('machine', 'Machine'), ('method', 'Method'), ('material', 'Material'), ('measurement', 'Measurement'), ('environment', 'Environment')], max_length=20)),
                ('description', models.TextField()),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('insufficient_evidence', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nonconformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_id', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('lot', models.CharField(blank=True, max_length=100)),
                ('process', models.CharField(blank=True, max_length=255)),
                ('defect_description', models.TextField(blank=True)),
                ('spec_violated', models.CharField(blank=True, max_length=255)),
                ('measured_value', models.CharField(blank=True, max_length=255)),
                ('required_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('locator', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('candidate_cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_refs', to='rcca.candidatecause')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nonconformance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='rcca.nonconformance')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_number', models.CharField(max_length=4)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('drafted', 'Drafted'), ('engineer_edited', 'Engineer-edited'), ('approved', 'Approved')], default='drafted', max_length=20)),
                ('agent_proposed_text', models.TextField(blank=True)),
                ('current_text', models.TextField(blank=True)),
                ('approver_name', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rcca.investigation')),
            ],
            options={
                'unique_together': {('investigation', 'd_number')},
            },
        ),
        migrations.AddField(
            model_name='candidatecause',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_causes', to='rcca.section'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('draft', 'Draft'), ('edit', 'Edit'), ('approve', 'Approve'), ('revert', 'Revert')], max_length=10)),
                ('actor', models.CharField(max_length=255)),
                ('from_state', models.CharField(blank=True, max_length=20)),
                ('to_state', models.CharField(blank=True, max_length=20)),
                ('text_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='rcca.investigation')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='rcca.section')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
